export const SOCCER_TEAMS = [
  "Manchester United",
  "Manchester City",
  "Liverpool",
  "Chelsea",
  "Arsenal",
  "Tottenham Hotspur",
  "Newcastle United",
  "Brighton",
  "Aston Villa",
  "Fulham",
  "Brentford",
  "Everton",
  "Nottingham Forest",
  "Luton Town",
  "Crystal Palace",
  "Wolves",
  "Ipswich Town",
  "Leicester City",
  "West Ham United",
  "Southampton",
  "Bournemouth",
  "Real Madrid",
  "Barcelona",
  "Atlético Madrid",
  "Valencia",
  "Sevilla",
  "Villarreal",
  "Real Sociedad",
  "Athletic Bilbao",
  "Getafe",
  "Mallorca",
  "Las Palmas",
  "Osasuna",
  "Bayern Munich",
  "Borussia Dortmund",
  "RB Leipzig",
  "Bayer Leverkusen",
  "VfB Stuttgart",
  "Schalke 04",
  "Eintracht Frankfurt",
  "Hoffenheim",
  "Mainz",
  "Paris Saint-Germain",
  "Olympique Marseille",
  "Lyon",
  "Lens",
  "Lille",
  "Nice",
  "AS Monaco",
  "Nantes",
  "Inter Milan",
  "AC Milan",
  "Juventus",
  "Napoli",
  "Lazio",
  "Roma",
  "Fiorentina",
  "Bologna",
  "Monza",
  "Torino",
  "Sassuolo",
  "Ajax",
  "PSV Eindhoven",
  "Feyenoord",
  "AZ Alkmaar",
  "Vitesse",
  "FC Twente",
  "Utrecht",
  "Benfica",
  "Porto",
  "Sporting CP",
  "Braga",
  "Celtic",
  "Rangers",
  "Galatasaray",
  "Fenerbahçe",
  "Besiktas",
  "Trabzonspor",
  "Olympiacos",
  "AEK Athens",
  "Panathinaikos",
];

export const COUNTRIES = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cape Verde",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czech Republic",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Vatican City",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const AVATAR_COLORS = [
  "#ef4444", "#f97316", "#eab308", "#22c55e", "#06b6d4", "#3b82f6", "#8b5cf6", "#ec4899",
  "#dc2626", "#ea580c", "#ca8a04", "#16a34a", "#0891b2", "#1d4ed8", "#7c3aed", "#be185d",
];

export const COUNTRY_FLAGS: Record<string, string> = {
  "Afghanistan": "🇦🇫",
  "Albania": "🇦🇱",
  "Algeria": "🇩🇿",
  "Andorra": "🇦🇩",
  "Angola": "🇦🇴",
  "Argentina": "🇦🇷",
  "Armenia": "🇦🇲",
  "Australia": "🇦🇺",
  "Austria": "🇦🇹",
  "Azerbaijan": "🇦🇿",
  "Bahamas": "🇧🇸",
  "Bahrain": "🇧🇭",
  "Bangladesh": "🇧🇩",
  "Barbados": "🇧🇧",
  "Belarus": "🇧🇾",
  "Belgium": "🇧🇪",
  "Belize": "🇧🇿",
  "Benin": "🇧🇯",
  "Bhutan": "🇧🇹",
  "Bolivia": "🇧🇴",
  "Bosnia and Herzegovina": "🇧🇦",
  "Botswana": "🇧🇼",
  "Brazil": "🇧🇷",
  "Brunei": "🇧🇳",
  "Bulgaria": "🇧🇬",
  "Burkina Faso": "🇧🇫",
  "Burundi": "🇧🇮",
  "Cambodia": "🇰🇭",
  "Cameroon": "🇨🇲",
  "Canada": "🇨🇦",
  "Cape Verde": "🇨🇻",
  "Central African Republic": "🇨🇫",
  "Chad": "🇹🇩",
  "Chile": "🇨🇱",
  "China": "🇨🇳",
  "Colombia": "🇨🇴",
  "Comoros": "🇰🇲",
  "Congo": "🇨🇬",
  "Costa Rica": "🇨🇷",
  "Croatia": "🇭🇷",
  "Cuba": "🇨🇺",
  "Cyprus": "🇨🇾",
  "Czech Republic": "🇨🇿",
  "Czechia": "🇨🇿",
  "Denmark": "🇩🇰",
  "Djibouti": "🇩🇯",
  "Dominica": "🇩🇲",
  "Dominican Republic": "🇩🇴",
  "Ecuador": "🇪🇨",
  "Egypt": "🇪🇬",
  "El Salvador": "🇸🇻",
  "Equatorial Guinea": "🇬🇶",
  "Eritrea": "🇪🇷",
  "Estonia": "🇪🇪",
  "Eswatini": "🇸🇿",
  "Ethiopia": "🇪🇹",
  "Fiji": "🇫🇯",
  "Finland": "🇫🇮",
  "France": "🇫🇷",
  "Gabon": "🇬🇦",
  "Gambia": "🇬🇲",
  "Georgia": "🇬🇪",
  "Germany": "🇩🇪",
  "Ghana": "🇬🇭",
  "Greece": "🇬🇷",
  "Grenada": "🇬🇩",
  "Guatemala": "🇬🇹",
  "Guinea": "🇬🇳",
  "Guinea-Bissau": "🇬🇼",
  "Guyana": "🇬🇾",
  "Haiti": "🇭🇹",
  "Honduras": "🇭🇳",
  "Hungary": "🇭🇺",
  "Iceland": "🇮🇸",
  "India": "🇮🇳",
  "Indonesia": "🇮🇩",
  "Iran": "🇮🇷",
  "Iraq": "🇮🇶",
  "Ireland": "🇮🇪",
  "Israel": "🇮🇱",
  "Italy": "🇮🇹",
  "Jamaica": "🇯🇲",
  "Japan": "🇯🇵",
  "Jordan": "🇯🇴",
  "Kazakhstan": "🇰🇿",
  "Kenya": "🇰🇪",
  "Kiribati": "🇰🇮",
  "Kuwait": "🇰🇼",
  "Kyrgyzstan": "🇰🇬",
  "Laos": "🇱🇦",
  "Latvia": "🇱🇻",
  "Lebanon": "🇱🇧",
  "Lesotho": "🇱🇸",
  "Liberia": "🇱🇷",
  "Libya": "🇱🇾",
  "Liechtenstein": "🇱🇮",
  "Lithuania": "🇱🇹",
  "Luxembourg": "🇱🇺",
  "Madagascar": "🇲🇬",
  "Malawi": "🇲🇼",
  "Malaysia": "🇲🇾",
  "Maldives": "🇲🇻",
  "Mali": "🇲🇱",
  "Malta": "🇲🇹",
  "Marshall Islands": "🇲🇭",
  "Mauritania": "🇲🇷",
  "Mauritius": "🇲🇺",
  "Mexico": "🇲🇽",
  "Micronesia": "🇫🇲",
  "Moldova": "🇲🇩",
  "Monaco": "🇲🇨",
  "Mongolia": "🇲🇳",
  "Montenegro": "🇲🇪",
  "Morocco": "🇲🇦",
  "Mozambique": "🇲🇿",
  "Myanmar": "🇲🇲",
  "Namibia": "🇳🇦",
  "Nauru": "🇳🇷",
  "Nepal": "🇳🇵",
  "Netherlands": "🇳🇱",
  "New Zealand": "🇳🇿",
  "Nicaragua": "🇳🇮",
  "Niger": "🇳🇪",
  "Nigeria": "🇳🇬",
  "North Korea": "🇰🇵",
  "North Macedonia": "🇲🇰",
  "Norway": "🇳🇴",
  "Oman": "🇴🇲",
  "Pakistan": "🇵🇰",
  "Palau": "🇵🇼",
  "Palestine": "🇵🇸",
  "Panama": "🇵🇦",
  "Papua New Guinea": "🇵🇬",
  "Paraguay": "🇵🇾",
  "Peru": "🇵🇪",
  "Philippines": "🇵🇭",
  "Poland": "🇵🇱",
  "Portugal": "🇵🇹",
  "Qatar": "🇶🇦",
  "Romania": "🇷🇴",
  "Russia": "🇷🇺",
  "Rwanda": "🇷🇼",
  "Saint Kitts and Nevis": "🇰🇳",
  "Saint Lucia": "🇱🇨",
  "Saint Vincent and the Grenadines": "🇻🇨",
  "Samoa": "🇼🇸",
  "San Marino": "🇸🇲",
  "Sao Tome and Principe": "🇸🇹",
  "Saudi Arabia": "🇸🇦",
  "Senegal": "🇸🇳",
  "Serbia": "🇷🇸",
  "Seychelles": "🇸🇨",
  "Sierra Leone": "🇸🇱",
  "Singapore": "🇸🇬",
  "Slovakia": "🇸🇰",
  "Slovenia": "🇸🇮",
  "Solomon Islands": "🇸🇧",
  "Somalia": "🇸🇴",
  "South Africa": "🇿🇦",
  "South Korea": "🇰🇷",
  "South Sudan": "🇸🇸",
  "Spain": "🇪🇸",
  "Sri Lanka": "🇱🇰",
  "Sudan": "🇸🇩",
  "Suriname": "🇸🇷",
  "Sweden": "🇸🇪",
  "Switzerland": "🇨🇭",
  "Syria": "🇸🇾",
  "Taiwan": "🇹🇼",
  "Tajikistan": "🇹🇯",
  "Tanzania": "🇹🇿",
  "Thailand": "🇹🇭",
  "Timor-Leste": "🇹🇱",
  "Togo": "🇹🇬",
  "Tonga": "🇹🇴",
  "Trinidad and Tobago": "🇹🇹",
  "Tunisia": "🇹🇳",
  "Turkey": "🇹🇷",
  "Turkmenistan": "🇹🇲",
  "Tuvalu": "🇹🇻",
  "Uganda": "🇺🇬",
  "Ukraine": "🇺🇦",
  "United Arab Emirates": "🇦🇪",
  "United Kingdom": "🇬🇧",
  "United States": "🇺🇸",
  "Uruguay": "🇺🇾",
  "Uzbekistan": "🇺🇿",
  "Vanuatu": "🇻🇺",
  "Vatican City": "🇻🇦",
  "Venezuela": "🇻🇪",
  "Vietnam": "🇻🇳",
  "Yemen": "🇾🇪",
  "Zambia": "🇿🇲",
  "Zimbabwe": "🇿🇼",
};

export const TEAM_LOGOS: Record<string, string> = {
  "Manchester United": "https://resources.premierleague.com/premierleague/badges/t1.svg",
  "Manchester City": "https://resources.premierleague.com/premierleague/badges/t43.svg",
  "Liverpool": "https://resources.premierleague.com/premierleague/badges/t14.svg",
  "Chelsea": "https://resources.premierleague.com/premierleague/badges/t8.svg",
  "Arsenal": "https://resources.premierleague.com/premierleague/badges/t3.svg",
  "Tottenham Hotspur": "https://resources.premierleague.com/premierleague/badges/t6.svg",
  "Newcastle United": "https://resources.premierleague.com/premierleague/badges/t4.svg",
  "Brighton": "https://resources.premierleague.com/premierleague/badges/t36.svg",
  "Aston Villa": "https://resources.premierleague.com/premierleague/badges/t7.svg",
  "Fulham": "https://resources.premierleague.com/premierleague/badges/t54.svg",
  "Brentford": "https://resources.premierleague.com/premierleague/badges/t94.svg",
  "Everton": "https://resources.premierleague.com/premierleague/badges/t11.svg",
  "Nottingham Forest": "https://resources.premierleague.com/premierleague/badges/t17.svg",
  "Luton Town": "https://resources.premierleague.com/premierleague/badges/t163.svg",
  "Crystal Palace": "https://resources.premierleague.com/premierleague/badges/t31.svg",
  "Wolves": "https://resources.premierleague.com/premierleague/badges/t39.svg",
  "Ipswich Town": "https://resources.premierleague.com/premierleague/badges/t40.svg",
  "Leicester City": "https://resources.premierleague.com/premierleague/badges/t26.svg",
  "West Ham United": "https://resources.premierleague.com/premierleague/badges/t21.svg",
  "Southampton": "https://resources.premierleague.com/premierleague/badges/t20.svg",
  "Bournemouth": "https://resources.premierleague.com/premierleague/badges/t131.svg",
  "Real Madrid": "https://upload.wikimedia.org/wikipedia/en/3/39/Real_Madrid_CF.svg",
  "Barcelona": "https://upload.wikimedia.org/wikipedia/en/4/47/FC_Barcelona_%282009%E2%80%9310%29_crest.svg",
  "Atlético Madrid": "https://upload.wikimedia.org/wikipedia/en/0/0c/Atl%C3%A9tico_Madrid.svg",
  "Valencia": "https://upload.wikimedia.org/wikipedia/en/c/ce/Valencia_CF.svg",
  "Sevilla": "https://upload.wikimedia.org/wikipedia/en/3/3b/Sevilla_FC.svg",
  "Villarreal": "https://upload.wikimedia.org/wikipedia/en/2/20/Villarreal_CF.svg",
  "Real Sociedad": "https://upload.wikimedia.org/wikipedia/en/2/24/Real_Sociedad_SAD.svg",
  "Athletic Bilbao": "https://upload.wikimedia.org/wikipedia/en/0/0e/Athletic_Club.svg",
  "Getafe": "https://upload.wikimedia.org/wikipedia/en/1/13/Getafe_CF.svg",
  "Mallorca": "https://upload.wikimedia.org/wikipedia/en/b/b1/RCD_Mallorca.svg",
  "Las Palmas": "https://upload.wikimedia.org/wikipedia/en/8/8c/UD_Las_Palmas.svg",
  "Osasuna": "https://upload.wikimedia.org/wikipedia/en/5/50/CA_Osasuna.svg",
  "Bayern Munich": "https://upload.wikimedia.org/wikipedia/en/1/1f/FC_Bayern_Munich_logo.svg",
  "Borussia Dortmund": "https://upload.wikimedia.org/wikipedia/en/6/60/Borussia_Dortmund_logo.svg",
  "RB Leipzig": "https://upload.wikimedia.org/wikipedia/en/7/7b/RB_Leipzig.svg",
  "Bayer Leverkusen": "https://upload.wikimedia.org/wikipedia/en/e/e0/Bayer_04_Leverkusen_logo.svg",
  "VfB Stuttgart": "https://upload.wikimedia.org/wikipedia/en/2/20/VfB_Stuttgart_1893_logo.svg",
  "Schalke 04": "https://upload.wikimedia.org/wikipedia/en/8/87/FC_Schalke_04.svg",
  "Eintracht Frankfurt": "https://upload.wikimedia.org/wikipedia/en/0/04/Eintracht_Frankfurt_Logo.svg",
  "Hoffenheim": "https://upload.wikimedia.org/wikipedia/en/0/0f/TSG_1899_Hoffenheim_logo.svg",
  "Mainz": "https://upload.wikimedia.org/wikipedia/en/1/1a/FSV_Mainz_05_logo.svg",
  "Paris Saint-Germain": "https://upload.wikimedia.org/wikipedia/en/a/a7/Paris_Saint-Germain_F.C..svg",
  "Olympique Marseille": "https://upload.wikimedia.org/wikipedia/en/0/0b/Olympique_de_Marseille_logo.svg",
  "Lyon": "https://upload.wikimedia.org/wikipedia/en/a/a7/Olympique_Lyonnais_logo.svg",
  "Lens": "https://upload.wikimedia.org/wikipedia/en/5/58/RC_Lens.svg",
  "Lille": "https://upload.wikimedia.org/wikipedia/en/0/0c/Lille_OSC.svg",
  "Nice": "https://upload.wikimedia.org/wikipedia/en/4/45/OGC_Nice_logo.svg",
  "AS Monaco": "https://upload.wikimedia.org/wikipedia/en/c/cf/AS_Monaco_FC.svg",
  "Nantes": "https://upload.wikimedia.org/wikipedia/en/e/ea/FC_Nantes_logo.svg",
  "Inter Milan": "https://upload.wikimedia.org/wikipedia/en/0/05/Inter_Milan.svg",
  "AC Milan": "https://upload.wikimedia.org/wikipedia/en/d/d0/AC_Milan.svg",
  "Juventus": "https://upload.wikimedia.org/wikipedia/en/9/9a/Juventus_FC.svg",
  "Napoli": "https://upload.wikimedia.org/wikipedia/en/2/2d/SSC_Napoli.svg",
  "Lazio": "https://upload.wikimedia.org/wikipedia/en/c/ce/S.S.Lazio_badge.svg",
  "Roma": "https://upload.wikimedia.org/wikipedia/en/f/f7/AS_Roma_logo_%282017%29.svg",
  "Fiorentina": "https://upload.wikimedia.org/wikipedia/en/a/a4/ACF_Fiorentina_badge.svg",
  "Bologna": "https://upload.wikimedia.org/wikipedia/en/1/14/FC_Bologna_1909_logo.svg",
  "Monza": "https://upload.wikimedia.org/wikipedia/en/f/f2/AC_Monza_badge.svg",
  "Torino": "https://upload.wikimedia.org/wikipedia/en/9/91/Torino_FC_Logo.svg",
  "Sassuolo": "https://upload.wikimedia.org/wikipedia/en/4/4f/US_Sassuolo_Calcio_badge.svg",
  "Ajax": "https://upload.wikimedia.org/wikipedia/en/7/79/AFC_Ajax.svg",
  "PSV Eindhoven": "https://upload.wikimedia.org/wikipedia/en/0/0c/PSV_Eindhoven.svg",
  "Feyenoord": "https://upload.wikimedia.org/wikipedia/en/6/61/Feyenoord.svg",
  "AZ Alkmaar": "https://upload.wikimedia.org/wikipedia/en/e/e5/AZ_Alkmaar_logo.svg",
  "Vitesse": "https://upload.wikimedia.org/wikipedia/en/d/db/Vitesse_Arnhem_Logo.svg",
  "FC Twente": "https://upload.wikimedia.org/wikipedia/en/2/2f/FC_Twente_logo.svg",
  "Utrecht": "https://upload.wikimedia.org/wikipedia/en/2/2a/FC_Utrecht_logo.svg",
  "Benfica": "https://upload.wikimedia.org/wikipedia/en/1/12/SL_Benfica.svg",
  "Porto": "https://upload.wikimedia.org/wikipedia/en/c/c6/FC_Porto.svg",
  "Sporting CP": "https://upload.wikimedia.org/wikipedia/en/1/11/Sporting_CP_logo.svg",
  "Braga": "https://upload.wikimedia.org/wikipedia/en/e/e9/SC_Braga_logo.svg",
  "Celtic": "https://upload.wikimedia.org/wikipedia/en/3/35/Celtic_FC.svg",
  "Rangers": "https://upload.wikimedia.org/wikipedia/en/d/d9/Rangers_FC.svg",
  "Galatasaray": "https://upload.wikimedia.org/wikipedia/en/e/ec/Galatasaray_crest.svg",
  "Fenerbahçe": "https://upload.wikimedia.org/wikipedia/en/0/0c/Fenerbah%C3%A7e_S.K._logo.svg",
  "Besiktas": "https://upload.wikimedia.org/wikipedia/en/3/3e/Beşiktaş_JK.svg",
  "Trabzonspor": "https://upload.wikimedia.org/wikipedia/en/c/c5/Trabzonspor_logo.svg",
  "Olympiacos": "https://upload.wikimedia.org/wikipedia/en/9/9f/Olympiacos_FC_logo.svg",
  "AEK Athens": "https://upload.wikimedia.org/wikipedia/en/a/a3/AEK_Athens_FC_Logo.svg",
  "Panathinaikos": "https://upload.wikimedia.org/wikipedia/en/7/7a/Panathinaikos_FC_Logo.svg",
};
